profil:
  snapshots: 32
  password: '@JbD$07rhF!dAziQ5y^nXxct4mVwBk#6'
  storage: \\192.168.100.10\Backup\BACKUP_Restic\Stefan\Profil
  include:
  - C:\Users\Stefan\Desktop
  - C:\Users\Stefan\Pictures
  - C:\Users\Stefan\Music
  - C:\Users\Stefan\Videos
  - C:\Users\Stefan\Downloads
  - C:\Users\Stefan\Documents
  - C:\Users\Stefan\Ubiquiti UniFi\data\backup
  - C:\Users\Stefan\AppData\Roaming\FileZilla
  - C:\Users\Stefan\AppData\Roaming\FreeFileSync
  - C:\Users\Stefan\AppData\Roaming\GIMP
  - C:\Users\Stefan\AppData\Roaming\HeidiSQL
  - C:\Users\Stefan\AppData\Roaming\inkscape
  - C:\Users\Stefan\AppData\Roaming\KeePassXC
  - C:\Users\Stefan\AppData\Roaming\LibreOffice
  - C:\Users\Stefan\AppData\Roaming\MediaMonkey5
  - C:\Users\Stefan\AppData\Roaming\Mozilla
  - C:\Users\Stefan\AppData\Roaming\Notepad++
  - C:\Users\Stefan\AppData\Roaming\Thunderbird
  - C:\Users\Stefan\AppData\Roaming\Blackmagic Design
  exclude:
  - Thumbs.db
  - '*.iso'
  - AI/**
  - '**/node_modules/**'
  - .lock*
  - GitHub
media:
  snapshots: 4
  password: UfER8SPt#&4Olv%W*H@YjxQudGBTpe$J
  storage: C:\Users\Stefan\Documents\GitHub\PyRestic\src\STORAGE
  include:
  - '**/*'
  - C:\Test
  exclude:
  - Thumbs.db
  - '*.iso'
  - '**/node_modules/**'
  - AI/**
  - .lock*
  - GitHub
